name: CI-Packing-all
on:
    push:
        branches: [main, dev-tty]
jobs:
    build-win64-release:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
                  cache: pip
                  architecture: x64
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r ./requirements_win.txt
            - name: Run packing
              run: |
                  pyinstaller ./main.spec
                  mkdir test
                  cp ./dist/main.exe ./test/hello.exe
            - name: Packing
              uses: actions/upload-artifact@v3
              with:
                  name: helloworld-old-origin
                  path: ./test
            - name: Packing
              uses: actions/upload-artifact@v3
              with:
                  name: test-Win-old
                  path: ./test