name: CI-Packing-all
on:
  push:
    branches: [main, dev-tty]
jobs:
  build-win64-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements_win.txt

      - name: Run packing
        run: |
          pyinstaller ./hello.spec
          mkdir test
          cp ./dist/hello.exe ./test/hello.exe

      - name: Read version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./actions/package.json
          property: version

      - name: Read description
        id: description
        uses: juliangruber/read-file-action@v1
        with:
          path: ./actions/description.txt

      - name: Packing zip
        run: |
          7z a -tzip ./test/ ./test/

      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.value}}
          release_name: hello v${{steps.version.outputs.value}}
          body: ${{steps.description.outputs.content}}

      - name: Upload asset to GitHub Release
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url}}
          asset_path: ./test/release.zip
          asset_name: hello.zip
          asset_content_type: application/zip
